---
version: "3.8"
services:
  app:
    build:
      context: .
      args:
        APP_UID: 1000
        APP_GID: 1000
    image: cruftbot_app
    command: ./scripts/serve
    depends_on:
      - db
    volumes:
      - .:/app
      - user:/home/app/.cache
    ports:
      - "8000:8000"
      - "9000:9000"
    environment:
      - DJANGO_SETTINGS_MODULE=cruftbot.infrastructure.settings.development
      - PYTHONPATH=/app/
      - PYTHONUNBUFFERED=1
      - CRUFTBOT_SITE_ID=1
      - CRUFTBOT_SECRET_KEY=52f0f84e0e004ad1b85a20d44803058096d76c22b0df4763a347ef7f38761e738b94320c0dff4a24a3ad9b817e0a87d9
      - CRUFTBOT_DATABASE_URL=psql://cruftbot:cruftbot@db:5432/cruftbot
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: cruftbot
      POSTGRES_USER: cruftbot
      POSTGRES_PASSWORD: cruftbot
volumes:
  user:
  db:
