#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Running check framework…"
DJANGO_SETTINGS_MODULE=cruftbot.infrastructure.settings.production poetry run django-admin check --deploy --fail-level WARNING

# @todo #311 Check framework failure: You have
#  'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but
#  you have not set CSRF_COOKIE_SECURE to True. Using a secure-only
#  CSRF cookie makes it more difficult for network traffic sniffers to
#  steal the CSRF token.

# @todo #311 Check framework failure: ALLOWED_HOSTS must not be empty
#  in deployment.

echo "==> Running migration linter…"
poetry run django-admin lintmigrations

echo "==> Running tests…"
poetry run coverage run -m django test tests/

echo "==> Running coverage report…"
poetry run coverage report --fail-under 100
