#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

echo "==> Running check framework…"
DJANGO_SETTINGS_MODULE=cruftbot.infrastructure.settings.production poetry run django-admin check --deploy --fail-level WARNING

# @todo #311 Check framework failure: Your SECURE_SSL_REDIRECT setting
#  is not set to True. Unless your site should be available over both
#  SSL and non-SSL connections, you may want to either set this setting
#  True or configure a load balancer or reverse-proxy server to
#  redirect all connections to HTTPS.

# @todo #311 Check framework failure: SESSION_COOKIE_SECURE is not set
#  to True. Using a secure-only session cookie makes it more difficult
#  for network traffic sniffers to hijack user sessions.

# @todo #311 Check framework failure: You have
#  'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but
#  you have not set CSRF_COOKIE_SECURE to True. Using a secure-only
#  CSRF cookie makes it more difficult for network traffic sniffers to
#  steal the CSRF token.

# @todo #311 Check framework failure: ALLOWED_HOSTS must not be empty
#  in deployment.

echo "==> Running migration linter…"
poetry run django-admin lintmigrations

echo "==> Running tests…"
poetry run coverage run -m django test tests/

echo "==> Running coverage report…"
poetry run coverage report --fail-under 100
